apiVersion: v1
kind: Service
metadata:
  name: coffee-queue-service
  namespace: coffee-queue
  labels:
    app: coffee-queue-app
spec:
  selector:
    app: coffee-queue-app
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
